name: ci

env:
  PLUGIN: tool_forcedcache

on:
  push:
    tags:
      - '*'

jobs:
  ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    with:
      disable_behat: true
